### ISSUE TITLE
Page not responsive

### ISSUE THREAD

**Issue by gekkowrld** [Ruchita1010/resume-generator#1]
The "stepper" section text is overflowing outside the circles that it is meant to be contained in. And the input validation doesn't exist/work

**Comment by gekkowrld** [comment]
This seems to be because I'm my browser blocks cross-origin requests. If possible maybe make the text be smaller for people who can be affected.

**Comment by Ruchita1010** [comment]
Thank you for creating an issue and providing feedback!
Regarding the 'stepper', there's no text in the circles, there are icons! And as you pointed out later, it must be due because of the browser not allowing cross-origin requests. 
And there's no input validation as such, except for the email input as its type is restricted to be 'email'. But I just realize that it won't be of any use if there's no submit button. 
For the page not responsive issue, it is kind of on purpose! It is actually not responsive below 500px, because I didn't want the resume preview to get all squeezed in and it even affected the layout of the resume. As of now, haven't of any solution for this.
And as for the text, I couldn't understand why should it be smaller?!

**Comment by gekkowrld** [comment]
I meant the "alt" text which was being displayed instead of the icons. But I realize that it will affect the icon size as well. So no need to change
